### PR TITLE
Pushing the questions array to Data.js

### LINKED ISSUE #46: creating the Data file
Creating the quiz.json file where we store the array of questions 

This user story is developed on the branch `Data`.
This branch is merged into the `master` branch after completion.

### PR DESCRIPTION
**Pull request by Moamin-AbuEwaida**
I created Data.js file to adding the questions array including the answers

### CODE REVIEW

**Comment by Moamin-AbuEwaida** [comment]
Just pushed a new commit for the quiz questions file, the file's name is quiz.json

**Comment by Moamin-AbuEwaida** [comment]
Just deleted data.js file
it's weird that I have lint:css error where there is no any errors appear at my VSCode :thinking: 
@rayanejsilva @Dabrytskaya  @JTLiberona

**Comment by rayanejsilva** [comment]
> Just deleted data.js file
> it's weird that I have lint:css error where there is no any errors appear at my VSCode 🤔
> @rayanejsilva @Dabrytskaya @JTLiberona

@Moamin-AbuEwaida I fixed the css errors, but it is complaining about html (**Inline style is not allowed**). It is not a good practice to have the style inside of html file. @Dabrytskaya I will fix it, okay?

**Comment by Moamin-AbuEwaida** [comment]
> @Moamin-AbuEwaida I fixed the css errors, but it is complaining about html (**Inline style is not allowed**). It is not a good practice to have the style inside of html file. @Dabrytskaya I will fix it, okay?

ookkkaaaaay got it
thanks @rayanejsilva

**Review by rayanejsilva — APPROVED** [review]

**Review by JTLiberona — APPROVED** [review]
I reviewed the changes that @rayanejsilva has made in CSS file and the HTML. 
I agree that styles shouldn't be as an inline code :)

**Pull request merged**
