### PR TITLE
functional store

### PR DESCRIPTION
**Pull request by rayanejsilva**

### CODE REVIEW

**Comment by Moamin-AbuEwaida** [comment]
is this edit coming from updating the main HYF repo ?? @rayanejsilva

**Review by JTLiberona — APPROVED** [review]
Oh, great! This should fix this error:

error: using this is not allowed (no-restricted-syntax) at client/src/data-access/local-storage/store.js:7:23:

**Comment by JTLiberona** [comment]
> is this edit coming from updating the main HYF repo ?? @rayanejsilva

Yes, it comes from there. I saw it from the repo as a change that Evan made 6 days ago.

**Review by Moamin-AbuEwaida — APPROVED** [review]
LGTM

**Pull request merged**
