### PR TITLE
questions_for_quiz

### LINKED ISSUE #5: Quiz preparing
- [x] finding questions for the quiz about JS
- [x] finding correct and incorrect answers  for JS quiz
- [x] add questions file to the repo
- [x] add questions to data.js

### PR DESCRIPTION
**Pull request by Dabrytskaya**
5 possible questions for our quiz with the correct answers in brackets

### CODE REVIEW

**Review by Moamin-AbuEwaida — APPROVED** [review]
I did some edits to the questions file by adding the list of correct and incorrect answers

**Comment by Moamin-AbuEwaida** [comment]
linting error of the header on the 1st line of the MD file (#  backlog , # Questions ) is not solvable which is weird !!

**Comment by JTLiberona** [comment]
The error is in the STORE.JS

error: using `this` is not allowed (no-restricted-syntax) at client/src/data-access/local-storage/store.js:7:23:

Im gonna take a deep dive into it on my lunch break ;)

**Comment by Moamin-AbuEwaida** [comment]
The error is in the STORE.JS
error: using `this` is not allowed (no-restricted-syntax) at client/src/data-access/local-storage/store.js:7:23:
Im gonna take a deep dive into it on my lunch break ;)
> I found solutions through a JASON file in the repo and solved them :grin:

**Review by rayanejsilva — APPROVED** [review]

**Review by rayanejsilva — APPROVED** [review]

**Pull request merged**
